<a href="https://colab.research.google.com/github/EmilyCY/CIFAR10-Image-Classification/blob/Kman/Simple_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a simple SVM model using Python 3 only

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.decomposition import PCA
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.decomposition import PCA

from sklearn import svm
from sklearn.linear_model import LogisticRegression

# Trying to load from pickle

In [12]:
#mount tar.gz to CoLab from Google Drive
from google.colab import files
uploaded_files = files.upload()

Saving cifar10python.tar.gz to cifar10python.tar.gz


In [2]:
#file structure i've given appears incorrect?? -need to resolve file structure or find different load method
!tar -cifar10 "G:\My Drive\Colab Notebooks\Machine Learning\Final project\cifar10python.tar.gz"

tar: G\:\\My Drive\\Colab Notebooks\\Machine Learning\\Final project\\cifar10python.tar.gz: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors


In [5]:
cifar10='cifar10python.tar.gz'
print(filename)

cifar10python.tar.gz


In [3]:
#methiod borrowed from https://www.programcreek.com/python/?CodeExample=load+cifar10
def load_CIFAR_10(filename,
                   file_type="train",
                   label_type="fine_labels"):
  """
  Load CIFAR 10 data set
  
  @param filename: file name of CIFAR 10
  @param file_type: "train" or "test"
  @param label_type: "fine_labels" or "coarse_labels"
  """
  datadict=pickle.load(open(filename, "rb"));
  
  X=datadict["data"];
  Y=datadict[label_type];
  
  if file_type=="train":
    X=X.reshape(50000, 3, 32, 32).transpose(0,2,3,1).astype("float");
  elif file_type=="test":
    X=X.reshape(10000, 3, 32, 32).transpose(0,2,3,1).astype("float");
    
  Y=np.array(Y);
    
  return X, Y; 

In [6]:
load_CIFAR_10(cifar10,train,fine_labels)

NameError: ignored

# Load CIFAR10 dataset(s) from torchvision library

This works successfully and means i either need to work in Pytorch, or need to convert datasets from Pytorch tensors to numpy ndarray

In [3]:
import torch
import torchvision
import torchvision.transforms as transforms

In [4]:
# import the training set (first 50,000 imgs) by setting train=True.
trainset = torchvision.datasets.CIFAR10(root='./data', train=True,download=True)
# import the test set (10,000 imgs) by setting train=False
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True)
# define the ten labels manually.
classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

  0%|          | 0/170498071 [00:00<?, ?it/s]

Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [5]:
#check the data is loaded correctly
#data sholuld be loaded as a tuple
print("This is the length of the trainset: ",len(trainset))
print("This is the length of the testset: ",len(testset))

This is the length of the trainset:  50000
This is the length of the testset:  10000


In [6]:
print(trainset)
print(testset)

Dataset CIFAR10
    Number of datapoints: 50000
    Root location: ./data
    Split: Train
Dataset CIFAR10
    Number of datapoints: 10000
    Root location: ./data
    Split: Test


In [7]:
path = "data/CIFAR10/"

In [8]:
#confirm what type trainset has been created as 
print(type(trainset))

<class 'torchvision.datasets.cifar.CIFAR10'>


In [9]:
print(testset.data)

[[[[158 112  49]
   [159 111  47]
   [165 116  51]
   ...
   [137  95  36]
   [126  91  36]
   [116  85  33]]

  [[152 112  51]
   [151 110  40]
   [159 114  45]
   ...
   [136  95  31]
   [125  91  32]
   [119  88  34]]

  [[151 110  47]
   [151 109  33]
   [158 111  36]
   ...
   [139  98  34]
   [130  95  34]
   [120  89  33]]

  ...

  [[ 68 124 177]
   [ 42 100 148]
   [ 31  88 137]
   ...
   [ 38  97 146]
   [ 13  64 108]
   [ 40  85 127]]

  [[ 61 116 168]
   [ 49 102 148]
   [ 35  85 132]
   ...
   [ 26  82 130]
   [ 29  82 126]
   [ 20  64 107]]

  [[ 54 107 160]
   [ 56 105 149]
   [ 45  89 132]
   ...
   [ 24  77 124]
   [ 34  84 129]
   [ 21  67 110]]]


 [[[235 235 235]
   [231 231 231]
   [232 232 232]
   ...
   [233 233 233]
   [233 233 233]
   [232 232 232]]

  [[238 238 238]
   [235 235 235]
   [235 235 235]
   ...
   [236 236 236]
   [236 236 236]
   [235 235 235]]

  [[237 237 237]
   [234 234 234]
   [234 234 234]
   ...
   [235 235 235]
   [235 235 235]
   [234 234

In [10]:
# Separating trainset/testset data/label
x_train = trainset.data
x_test = testset.data
y_train = trainset.targets
y_test = testset.targets

In [11]:
#Set the example index
example=199

In [12]:
print(type(x_train))
print(x_train[example])

<class 'numpy.ndarray'>
[[[167 178 196]
  [163 174 192]
  [163 174 192]
  ...
  [166 177 196]
  [165 176 195]
  [165 176 195]]

 [[169 180 198]
  [166 177 195]
  [166 177 195]
  ...
  [170 182 198]
  [169 180 197]
  [168 179 196]]

 [[168 179 197]
  [167 178 196]
  [167 178 196]
  ...
  [173 185 200]
  [172 184 198]
  [171 183 197]]

 ...

 [[ 94 102 112]
  [ 88  95 105]
  [ 94 101 111]
  ...
  [106 113 123]
  [103 110 120]
  [104 111 121]]

 [[ 90  97 107]
  [ 89  96 106]
  [ 86  92 103]
  ...
  [106 112 123]
  [ 92  99 109]
  [ 95 102 112]]

 [[111 114 126]
  [ 97 100 112]
  [ 91  95 106]
  ...
  [108 111 123]
  [ 96  99 111]
  [ 96 100 111]]]


In [14]:
# Configuration of HOG descriptor
normalize = True          #  True ==> yields a little bit better score
                          #  
block_norm = 'L2-Hys'     # or 'L1'
orientations = 9          # 
pixels_per_cell = [8, 8]  #  see section 'Additional remarks' for some explanation
cells_per_block = [2, 2]  # 

def extractFeature(img, vis=False):
    from skimage.feature import hog
    return hog(img, orientations, pixels_per_cell, cells_per_block, block_norm, visualise=vis, transform_sqrt=normalize)

In [15]:
# extracting one sample data
nfeatures = extractFeature(x_train[example], vis=False).size
print('Number of features = {}'.format(nfeatures))

fig, axarr = plt.subplots(3,len(examples_id), figsize=(16,5))
for i in range(len(examples_id)):
    id = examples_id[i]
    axarr[0,i].imshow(trainset[id][0][:,:])
    axarr[0,i].axis('off')
    axarr[1,i].imshow(x_train[id],cmap='gray')
    axarr[1,i].axis('off')
    _, hog_vis = extractFeature(x_train[id], vis=True)
    axarr[2,i].imshow(hog_vis,cmap='gray')
    axarr[2,i].axis('off')
plt.show()

TypeError: ignored

# Applied PCA to the Features of Cifar

In [ ]:
pca = PCA()
pca.fit_transform(x_train)